### ISSUE TITLE
PHP parse error in the PagesAsset bundle

### ISSUE THREAD

**Issue by rochdi80tn** [dmstr/yii2-pages-module#2]
### PHP Parse Error – yii\base\ErrorException

syntax error, unexpected '.', expecting ',' or ';'
_line 16_

``` php
14: class PagesAsset extends AssetBundle
15: {
16:     public $sourcePath = __DIR__.'/less';
17:     public $css = [
18:         'module.less'
19:     ];
20: }
```

I've fixed this locally by addint `init()` function as bellow and removing the initialization of the `public $sourcePath` :

``` php
class PagesAsset extends AssetBundle
{
    public $sourcePath ;
    public $css = [
        'module.less'
    ];

    public function init() {
        parent::init();
        $this->sourcePath = __DIR__.'/less';
    }

}
```

I am using below PHP version and not sure whether this is related to this or not

> PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 

Thanks.

**Comment by schmunk42** [comment]
Looks like you don't have `__DIR__` set.
Would `@vendor/dmstr/modules/pages/assets/less` work?
