### ISSUE TITLE
Problem with migration

### ISSUE THREAD

**Issue by ntesic** [dmstr/yii2-pages-module#20]
When doing migration, on Mysql 5.7 getting this error:
```
Error: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: ALTER TABLE `dmstr_page` ADD UNIQUE INDEX `name_id_UNIQUE` (`name_id`)
    > create unique index name_id_UNIQUE on dmstr_page (name_id) ...
```

How to solve this?

**Comment by schmunk42** [comment]
I've activated tests in Travis with MySQL 5.7, migrations run fine there, see https://travis-ci.org/dmstr/yii2-pages-module/builds/246365513

Which `yii2-pages` version are you using? Do you use native MySQL, MariaDB or Percona?

**Comment by ntesic** [comment]
Server version: 10.1.22-MariaDB- Debian 9.0
and yii2-pages version is latest I guess,
from composer:
`"dmstr/yii2-pages-module": "*"`

**Comment by schmunk42** [comment]
You can use `composer show` to list your installed versions.

I've added the MariaDB version you've mentioned to the testing setup: https://travis-ci.org/dmstr/yii2-pages-module/jobs/247012155#L357 - also green?!

**Comment by ntesic** [comment]
dmstr/yii2-pages-module              0.15.2

**Comment by schmunk42** [comment]
That's "quite old", current release is 0.21.8 - https://github.com/dmstr/yii2-pages-module/releases

Could you make a backup of your data and try to test an up-to-date version?
