### ISSUE TITLE
Illegal string offset 'data-page-id' exception trown

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/yii2-pages-module#25]
I'm using '*' as access_domain value and I get exception [here](https://github.com/dmstr/yii2-pages-module/blob/master/models/Tree.php#L254)

At some moment this functions was called with '*' as a value of `linkOption` parameter. And `ArrayHelper::merge` is crashing as it suppose to merge two arrays, but we have string as first parameter. Can't understand what's happened. Maybe last update caused it.

**Comment by StalkAlex** [comment]
I think problem in backend library [here](https://github.com/dmstr/yii2-backend-module/blob/master/src/views/layouts/_sidebar.php#L42)

Current packagist version differ from master

```php
echo \dmstr\widgets\Menu::widget(
    [
        'options' => ['class' => 'sidebar-menu'],
        'encodeLabels' => false,
        'items' => \yii\helpers\ArrayHelper::merge(
            ['items' => ['label' => 'Backend navigation', 'options' => ['class' => 'header']]],
            \dmstr\modules\pages\models\Tree::getMenuItems('backend', true, \dmstr\modules\pages\models\Tree::GLOBAL_ACCESS_DOMAIN)
        ),
    ]
);
```
Note the third parameter causing this exception in `getMenyItems` call. Please release next version of backend module.

**Comment by schmunk42** [comment]
Just for confirmation, which version of `yii2-backend-module` do you have? 
RC4 is even with master ... https://github.com/dmstr/yii2-backend-module/releases/tag/0.7.0-rc4
If you're on `stable` you might not have gotten this update.

**Comment by StalkAlex** [comment]
Yes, we're on stable. 0.6.0 is installed now.

**Comment by schmunk42** [comment]
Will create the `0.7.0` release for the *backend* module ASAP, in the meantime there's a `0.6.1` which forces *pages* to be `<0.22`.

Thank you for reporting!

**Comment by StalkAlex** [comment]
No problem, thanks!

**Comment by schmunk42** [comment]
Added 0.7.0 also (same ad 0.7.0-rc4)
