### ISSUE TITLE
Discussion: Disable bootstrapping of module

### ISSUE THREAD

**Issue by schmunk42** [dmstr/yii2-pages-module#5]
see 
- https://github.com/dmstr/yii2-cms-metapackage/issues/2#issuecomment-203540627
- https://github.com/dmstr/yii2-pages-module/blob/master/Bootstrap.php

**Comment by StalkAlex** [comment]
There is no bootstrap.php config in Phundament, isn't there? 
https://github.com/yiisoft/yii2/issues/11236#issuecomment-203786216

**Comment by schmunk42** [comment]
You can use the beginning of `main.php`, right below setAlias(es).
