### ISSUE TITLE
error when running migrate

### ISSUE THREAD

**Issue by cornernote** [dmstr/yii2-pages-module#9]
Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

Happens on this migration:
https://github.com/dmstr/yii2-pages-module/blob/master/migrations/m150309_153255_create_tree_manager_table.php

**Comment by cornernote** [comment]
seems it's due to an old version of mysql

http://stackoverflow.com/a/17498167/599477

**Comment by cornernote** [comment]
would still be nice to have some workaround, as mysql 5.5 is the default for ubuntu 14.04

if not, it's fine, i'll just tweak that migration manually

**Comment by schmunk42** [comment]
A PR would be great. 

Can we simple remove the expression? 

CC: @handcode

**Comment by cornernote** [comment]
If you use timestamp behaviour it can be removed, is that an acceptable solution? If so I'll do a PR.

**Comment by schmunk42** [comment]
What's about other databases (PostGre, SQLite)?

**Comment by cornernote** [comment]
Can you extend the unit tests to check the other databases?

There is a travis test suite running in a similar way here:
https://github.com/bedezign/yii2-audit/blob/master/.travis.yml

With created_at/updated_at fields I think the safer solution is to use timestamp behavior because you're not relying on any database specific functionality.  The cost is minimal to attach and run the behavior, and seems worth the tradeoff to achieve independence from the database.
